### ISSUE TITLE
Add package "tzdata" to allow manually setting timezone

### ISSUE THREAD

**Issue by synthic** [eggbean/docker-weechat#3]
Hello, is there any way you can add the package `tzdata` to the list of installed packages in the Dockerfile? For Alpine based images, this is required so that the timezone can be set manually with the commonly used `TZ` environment variable. This is useful to me because when running images on a Synology device, you aren't allowed to mount `/etc/localtime` or anything on the host that is owned by root.

References:
https://grainger.xyz/timezone-in-docker-alpine-not-using-environment-variable-tz
https://github.com/gliderlabs/docker-alpine/issues/136

**Comment by eggbean** [comment]
@synthic 
Hi, sorry I only just read your message. I have turned on notifications now.
I have added tzdata to the Dockerfile now, if you still need this. 
A new build should be available on docker hub in a few minutes.

**Comment by synthic** [comment]
Thank you! Now I can correctly set the timezone by adding the `TZ` environment variable. I appreciate you making the change.
